aws_access_key_id_west = "your-access-key-id"
aws_secret_access_key_west = "your-secret-access-key"
ami_id_west = "ami-0648742c7600c103f"
instance_type = "t2.micro"
key_name = "mongo"
ssh_public_key = "your-ssh-public-key"
